version: '3'
services:
    apache:
        build:
            ./apache
        ports:
            - '8080:8080'
        volumes:
            - ./apache/httpd.conf:/usr/local/apache2/conf/httpd.conf
    nginx:
        build:
            ./nginx
        ports:
            - 80:80
        volumes:
            - ./nginx/nginx.conf:/etc/nginx/nginx.conf        
    mysql:
        build:
            ./mysql
        ports:
            - '3306:3306'
        environment:
            MYSQL_ROOT_PASSWORD: ""
    php:
        build:
            ./php
        volumes:
            - ./php:/var/www
    